services:
  - type: web
    name: smart-gst-intelligence-system
    env: python
    buildCommand: apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng && pip install -r requriments.txt
    startCommand: uvicorn backend.mainn:app --host 0.0.0.0 --port 10000 